---
title: "Table"
author: "Jeremiah Jones"
date: "3/21/2021"
output: 
  pdf_document:
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

## Load Results

```{r load}
library(ggplot2)
library(qs)
library(dplyr)

suffix <- "ml0-9-2.qs"
files <- dir("./results/", "*.qs", full.names = T)
files <- files[grep(paste0("result-\\d+-.+", suffix), files, perl=T)]

all_results <- lapply(files, qread, nthreads=2) %>% bind_rows
all_results <- all_results %>% mutate(
  # NIE = if_else(coef_setting == "small", 48*n^(-1/2), 2.4),
  # NDE = 2,
  # coverage_NDE = (lower_NDE <= NDE) & (NDE <= upper_NDE),
  # coverage_NIE = (lower_NIE <= NIE) & (NIE <= upper_NIE),
  scenario = toupper(scenario),
  inf_method = if_else(inf_method == "minner", "minnier", inf_method) # fix typo
)
all_results <- all_results %>% 
  mutate(model_version = factor(model_version, levels=c(
    "product", "mixture", "adaptive", "full", "oracle"
  )))
```

## Including Plots


```{r table}
library(kableExtra)
all_results %>% filter(inf_method=="naive_boot") %>% 
  filter(model_version %in% c("product", "mixture", "adaptive")) %>% 
  group_by(coef_setting, n, model_version, use_sl) %>% 
  summarize(PC = mean(num_missed == 0), 
            MN = median(num_noise)) %>% 
  # mutate(scenario=toupper(scenario),
  #        val=if_else(col == "is_missed", 1-val, val),
  #        col=if_else(col == "is_missed", "PC", "MN")) %>% 
  # tidyr::pivot_wider(id_cols=c(coefs, n, weight_name, SL), 
  #                    names_from=c(scenario, col),
  #                    names_glue="{scenario}_{col}",
  #                    values_from=val) %>% 
  arrange(coef_setting, n, desc(model_version), use_sl) %>% 
  kbl(booktabs=T, align="c", digits=2L, ) %>% 
  column_spec(1:2, bold=T) %>% 
  collapse_rows(1:2, latex_hline = "major", valign = "middle")
```

